# Generated by Django 5.2.14 on 2026-05-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorder',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorder',
            name='order_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
