# Generated by Django 5.2.14 on 2026-05-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customorder_address_customorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='pheta_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
