# Generated by Django 5.2.14 on 2026-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customorder_quantity_alter_customorder_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='selected_pheta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
