# Generated by Django 5.2.14 on 2026-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customorder_selected_pheta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='pheta_type',
        ),
    ]
